# Choose std-devs to be about the maximum error in a time-step
# See: http://nbviewer.ipython.org/github/balzer82/Kalman/blob/master/Extended-Kalman-Filter-CTRV.ipynb?create=1
# More infos: https://github.com/lms-org/config_auto_drive/blob/master/configs/ego.xml
kalman_cov:
    filter_init_var_x: 0.01
    filter_init_var_y: 0.01
    filter_init_var_a: 0.01
    filter_init_var_v: 0.01
    filter_init_var_theta: 0.01
    filter_init_var_omega: 0.01
    sys_var_x: 0.001
    sys_var_y: 0.001
    sys_var_a: 0.0024
    sys_var_v: 0.0004
    sys_var_theta: 0.008
    sys_var_omega: 0.03
